### PR TITLE
CAPZ support

### PR DESCRIPTION
**Pull request by bavarianbidi**
PR brings the following new metrics from `cluster-api-provider-azure` CRs:

```
capi_azurecluster_annotation_paused
capi_azurecluster_created
capi_azurecluster_info
capi_azurecluster_owner
capi_azurecluster_status_conditions
capi_azurecluster_status_ready
capi_azuremachine_annotation_paused
capi_azuremachine_created
capi_azuremachine_info
capi_azuremachine_owner
capi_azuremachine_status_addresses
capi_azuremachine_status_conditions
capi_azuremachine_status_ready
capi_azuremachinepool_annotation_paused
capi_azuremachinepool_created
capi_azuremachinepool_info
capi_azuremachinepool_owner
capi_azuremachinepool_status_addresses
capi_azuremachinepool_status_conditions
capi_azuremachinepool_status_image_info
capi_azuremachinepool_status_ready
capi_azuremachinepool_status_replicas
capi_azuremachinepoolmachine_annotation_paused
capi_azuremachinepoolmachine_created
capi_azuremachinepoolmachine_owner
capi_azuremachinepoolmachine_status_conditions
capi_azuremachinepoolmachine_status_image_info
capi_azuremachinepoolmachine_status_latest_model_applied
capi_azuremachinepoolmachine_status_ready
capi_azuremachinepoolmachine_status_version
```

# `capi_azurecluster_status_conditions`
```
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="LoadBalancersReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="NATGatewaysReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="NetworkInfrastructureReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="PublicIPsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="Ready",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="ResourceGroupReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="RouteTablesReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="SecurityGroupsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="SubnetsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="False",type="VNetReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="LoadBalancersReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="NATGatewaysReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="NetworkInfrastructureReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="PublicIPsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="Ready",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="ResourceGroupReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="RouteTablesReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="SecurityGroupsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="SubnetsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="True",type="VNetReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="LoadBalancersReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="NATGatewaysReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="NetworkInfrastructureReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="PublicIPsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="Ready",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="ResourceGroupReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="RouteTablesReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="SecurityGroupsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="SubnetsReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
capi_azurecluster_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",status="Unknown",type="VNetReady",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 0
```

# `capi_azurecluster_info`
```
capi_azurecluster_info{cluster_name="marioc1",control_plane_endpoint_ip="marioc1-d1107536.westeurope.cloudapp.azure.com",control_plane_endpoint_port="6443",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",location="westeurope",name="marioc1",namespace="org-multi-project",resource_group="marioc1",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
```

# `capi_azurecluster_status_ready`
```
capi_azurecluster_status_ready{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
```

# `capi_azurecluster_created`
```
capi_azurecluster_created{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1.672752467e+09
```

# `capi_azurecluster_owner`
```
capi_azurecluster_owner{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureCluster",name="marioc1",namespace="org-multi-project",owner_is_controller="true",owner_kind="Cluster",owner_name="marioc1",owner_uid="dd5ed135-1a9a-4687-97da-8133af09cf13",uid="4bd1e014-07b2-4680-8867-51667dc03395",version="v1beta1"} 1
```

# `capi_azuremachinepoolmachine_status_conditions`
```
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="False",type="NodeHealthy",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 0
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="False",type="Ready",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 0
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="True",type="NodeHealthy",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="True",type="Ready",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="Unknown",type="NodeHealthy",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 0
capi_azuremachinepoolmachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",status="Unknown",type="Ready",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 0
capi_azuremachinepoolmachine_status_ready{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepoolmachine_status_latest_model_applied{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepoolmachine_status_version{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",provisioning_state="v1.24.8",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepoolmachine_created{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1.672752766e+09
capi_azuremachinepoolmachine_owner{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePoolMachine",name="marioc1-def00-3830f64e-0",namespace="org-multi-project",owner_kind="AzureMachinePool",owner_name="marioc1-def00-3830f64e",owner_uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",uid="a9ff444d-f73d-4d58-b81a-9a7d72bead8f",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="False",type="BootstrapSucceeded",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="False",type="Ready",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="False",type="ScaleSetDesiredReplicas",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="False",type="ScaleSetModelUpdated",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="False",type="ScaleSetRunning",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="True",type="BootstrapSucceeded",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="True",type="Ready",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="True",type="ScaleSetDesiredReplicas",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="True",type="ScaleSetModelUpdated",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="True",type="ScaleSetRunning",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="Unknown",type="BootstrapSucceeded",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="Unknown",type="Ready",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="Unknown",type="ScaleSetDesiredReplicas",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="Unknown",type="ScaleSetModelUpdated",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
capi_azuremachinepool_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",status="Unknown",type="ScaleSetRunning",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 0
```

# `capi_azuremachinepool_info`
```
capi_azuremachinepool_info{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",location="westeurope",name="marioc1-def00-3830f64e",namespace="org-multi-project",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
```

# `capi_azuremachinepool_status_ready`
```
capi_azuremachinepool_status_ready{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
```

# `capi_azuremachinepool_status_replicas`
```
capi_azuremachinepool_status_replicas{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
```

# `capi_azuremachinepool_status_image_info`
```
capi_azuremachinepool_status_image_info{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",offer="capi",publisher="cncf-upstream",sku="ubuntu-2004-gen1",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="124.8.20221129"} 1
```

# `capi_azuremachinepool_created`
```
capi_azuremachinepool_created{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1.672752467e+09
```

# `capi_azuremachinepool_owner`
```
capi_azuremachinepool_owner{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachinePool",name="marioc1-def00-3830f64e",namespace="org-multi-project",owner_is_controller="true",owner_kind="MachinePool",owner_name="marioc1-def00",owner_uid="a0265b96-6b70-4a9a-b72b-9a4c2d3587d3",uid="c7690fff-dad1-431e-ab63-7ae18f0bdc9e",version="v1beta1"} 1
```

# `capi_azuremachine_status_conditions`
```
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="BootstrapSucceeded",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="DisksReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="InboundNATRulesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="NetworkInterfacesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="Ready",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="False",type="VMRunning",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="BootstrapSucceeded",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="DisksReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="InboundNATRulesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="NetworkInterfacesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="Ready",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="True",type="VMRunning",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="BootstrapSucceeded",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="DisksReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="InboundNATRulesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="NetworkInterfacesReady",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="Ready",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
capi_azuremachine_status_conditions{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",status="Unknown",type="VMRunning",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 0
```

# `capi_azuremachine_info`
```
capi_azuremachine_info{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",os_disk_size="50",subnet="control-plane-subnet",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1",vm_size="Standard_D4s_v3"} 1
```

# `capi_azuremachine_status_ready`
```
capi_azuremachine_status_ready{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
```

# `capi_azuremachine_created`
```
capi_azuremachine_created{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1.672752573e+09
```

# `capi_azuremachine_owner`
```
capi_azuremachine_owner{cluster_name="marioc1",group="infrastructure.cluster.x-k8s.io",kind="AzureMachine",name="marioc1-control-plane-a72bcf8f-lksgv",namespace="org-multi-project",owner_is_controller="true",owner_kind="Machine",owner_name="marioc1-jjxd5",owner_uid="b66987fc-51b6-4bed-bfbe-74e3537b6d2a",uid="cb65baeb-eb64-4257-a8d5-c69b65467aed",version="v1beta1"} 1
```

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [x] metric name change doesn't affect existing alerts

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Can you add information in the PR description? Initial support for what?

**Comment by bavarianbidi** [comment]
> Can you add information in the PR description? Initial support for what?

i changed the description, as it's still in WIP. Will update everything once i'm done with the implementation

**Comment by QuentinBisson** [comment]
Thank you :) Do you think I can release the current main branch so the app is deployed on all CAPI providers (but CAPZ) without issues?

**Review by primeroz — APPROVED** [review]
LGTM

on a side note though, it seems like `merge to main` is allowed on this repo with no approval. Should we change repo settings ?

**Comment by bavarianbidi** [comment]
> LGTM
> 
> on a side note though, it seems like `merge to main` is allowed on this repo with no approval. Should we change repo settings ?

thx for the hint - i've enabled branch protection

**Comment by QuentinBisson** [comment]
Hey can we move the image to 2.8.0?

**Comment by bavarianbidi** [comment]
> Hey can we move the image to 2.8.1? I'm asking because you set up a custom tag

https://github.com/giantswarm/cluster-api-monitoring-app/pull/38

**Comment by QuentinBisson** [comment]
Thank you :) BTW, my main reason for asking is we need something similar for VPA CR and I want to add this to our current KSM which iis relying on a stable tag, so yes i can :)

**Pull request merged**
